# Load -> Clean -> Understand -> Questions/Answers -> Exploratory Data Analysis(EDA) -> Save

In [3]:
import pandas as pd
import numpy as np

data={
    'Name':   ['Pavan', 'Narasimha', 'Divya', 'Rahim Sir', 'Pathi Sir',
                'Swetha', 'Uday', 'Yasmin', 'Saddam'],
    'Age':    [25, np.nan, 22, np.nan, 33, 18, 0, 13, 36],
    'Score':  [30, 95, np.nan, 88, np.nan, 72, 60, np.nan, 74],
    'Salary': [8000, np.nan, 20000, 15000, np.nan, 3000, 1, 2500, np.nan],
    'Grade':  ['F', 'A', None, 'A+', 'B', None, 'C', '', 'C'],
    'Passion':['Fish','Cricket','Skippin','Studies','Football','Drawing',45,'Reading','Singing']
}
df=pd.DataFrame(data)
df

df.to_csv("SchoolFriendsData.csv",index=False)
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

# df.isnull(),.isnull().sum(),.isnull().sum().sum()......  # Shows Nan Or None Values

In [2]:
df1=df.isnull() # isnull() show True means NaN or None values and False valid Values
df1

    Name    Age  Score  Salary  Grade  Passion
0  False  False  False   False  False    False
1  False   True  False    True  False    False
2  False  False   True   False   True    False
3  False   True  False   False  False    False
4  False  False   True    True  False    False
5  False  False  False   False   True    False
6  False  False  False   False  False    False
7  False  False   True   False  False    False
8  False  False  False    True  False    False

In [4]:
df11=df.isnull().sum() # isnull().sum() NaN or None values column wise
df11

Name       0
Age        2
Score      3
Salary     3
Grade      2
Passion    0
dtype: int64

In [6]:
df111=df.isnull().sum().sum() # Whole table NaN or None Values you have
df111

np.int64(10)

In [ ]:
# df=df.dropna(),.dropna(subset=['']),.dropna(axis=1) # Drops the Nan or None Values

In [7]:
df2=df.dropna() # Drops all NaN or None values , shows only valid row values
df2

    Name   Age  Score  Salary Grade Passion
0  Pavan  25.0   30.0  8000.0     F    Fish
6   Uday   0.0   60.0     1.0     C      45

In [9]:
df22=df.dropna(subset=['Age']) # drop N,None values in Age Column it shows only valid values in Age
df22

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
2      Divya  22.0    NaN  20000.0  None   Skippin
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

In [17]:
df222=df.dropna(subset=['Salary','Score','Grade']) # drops Nan,None values in Salary,Score,Grade.It shows only valid values of Salar,Score,Grade
df222

        Name   Age  Score   Salary Grade  Passion
0      Pavan  25.0   30.0   8000.0     F     Fish
3  Rahim Sir   NaN   88.0  15000.0    A+  Studies
6       Uday   0.0   60.0      1.0     C       45

In [15]:
df2222=df.dropna(axis=1)
df2222

        Name   Passion
0      Pavan      Fish
1  Narasimha   Cricket
2      Divya   Skippin
3  Rahim Sir   Studies
4  Pathi Sir  Football
5     Swetha   Drawing
6       Uday        45
7     Yasmin   Reading
8     Saddam   Singing

# df=df.fillna(), .fillna(df[''].mean()), .fillna(df[''].max())........ # Filling the Data with necessary inputs

In [19]:
df3=df.fillna(56) 
df3

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha  56.0   95.0     56.0     A   Cricket
2      Divya  22.0   56.0  20000.0    56   Skippin
3  Rahim Sir  56.0   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0   56.0     56.0     B  Football
5     Swetha  18.0   72.0   3000.0    56   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0   56.0   2500.0         Reading
8     Saddam  36.0   74.0     56.0     C   Singing

In [20]:
df33=df.fillna(df['Age'].mean())
df33

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha  21.0   95.0     21.0     A   Cricket
2      Divya  22.0   21.0  20000.0  21.0   Skippin
3  Rahim Sir  21.0   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0   21.0     21.0     B  Football
5     Swetha  18.0   72.0   3000.0  21.0   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0   21.0   2500.0         Reading
8     Saddam  36.0   74.0     21.0     C   Singing

In [23]:
# Shortcut for filling all columns at a time
df333=df.fillna({
    'Age':df['Age'].mean(),
    'Score':df['Score'].max(),
    'Salary':df['Salary'].std(),
    'Grade':df['Grade'].ffill()
})

df333

        Name   Age  Score        Salary Grade   Passion
0      Pavan  25.0   30.0   8000.000000     F      Fish
1  Narasimha  21.0   95.0   7901.799384     A   Cricket
2      Divya  22.0   95.0  20000.000000     A   Skippin
3  Rahim Sir  21.0   88.0  15000.000000    A+   Studies
4  Pathi Sir  33.0   95.0   7901.799384     B  Football
5     Swetha  18.0   72.0   3000.000000     B   Drawing
6       Uday   0.0   60.0      1.000000     C        45
7     Yasmin  13.0   95.0   2500.000000         Reading
8     Saddam  36.0   74.0   7901.799384     C   Singing