# A> Load -> B> Clean -> C> Understand -> D> Questions/Answers -> E> Exploratory Data Analysis(EDA) -> F> Save

In [ ]:
# Read The Data and Save

In [2]:
import pandas as pd
import numpy as np

data={
    'Name':   ['Pavan', 'Narasimha', 'Divya', 'Rahim Sir', 'Pathi Sir',
                'Swetha', 'Uday', 'Yasmin', 'Saddam'],
    'Age':    [25, np.nan, 22, np.nan, 33, 18, 0, 13, 36],
    'Score':  [30, 95, np.nan, 88, np.nan, 72, 60, np.nan, 74],
    'Salary': [8000, np.nan, 20000, 15000, np.nan, 3000, 1, 2500, np.nan],
    'Grade':  ['F', 'A', None, 'A+', 'B', None, 'C', '', 'C'],
    'Passion':['Fish','Cricket','Skippin','Studies','Football','Drawing',45,'Reading','Singing']
}
df=pd.DataFrame(data)
df

df.to_csv("SchoolFriendsData.csv",index=False)
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

In [ ]:
# Explore Data Frame

In [37]:
df.columns

Index(['Name', 'Age', 'Score', 'Salary', 'Grade', 'Passion'], dtype='object')

In [38]:
df.index

RangeIndex(start=0, stop=9, step=1)

In [39]:
df.shape

(9, 6)

In [40]:
df.dtypes

Name        object
Age        float64
Score      float64
Salary     float64
Grade       object
Passion     object
dtype: object

In [41]:
df.head(5) # First 5 rows

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football

In [42]:
df.tail(5) # last 5 rows

        Name   Age  Score  Salary Grade   Passion
4  Pathi Sir  33.0    NaN     NaN     B  Football
5     Swetha  18.0   72.0  3000.0  None   Drawing
6       Uday   0.0   60.0     1.0     C        45
7     Yasmin  13.0    NaN  2500.0         Reading
8     Saddam  36.0   74.0     NaN     C   Singing

In [43]:
df.nunique() # Unique values per column

Name       9
Age        7
Score      6
Salary     6
Grade      6
Passion    9
dtype: int64

In [44]:
df.sample(5) # 5 Randam rows values

        Name   Age  Score   Salary Grade  Passion
5     Swetha  18.0   72.0   3000.0  None  Drawing
6       Uday   0.0   60.0      1.0     C       45
1  Narasimha   NaN   95.0      NaN     A  Cricket
2      Divya  22.0    NaN  20000.0  None  Skippin
7     Yasmin  13.0    NaN   2500.0        Reading

In [45]:
df.info() # shows Range,columns,df,dtypes,memory

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     9 non-null      object
 1   Age      7 non-null      float64
 2   Score    6 non-null      float64
 3   Salary   6 non-null      float64
 4   Grade    7 non-null      object
 5   Passion  9 non-null      object
dtypes: float64(3), object(3)
memory usage: 564.0+ bytes

In [46]:
df.value_counts() # All valid rows withoght NaN or None values

Name   Age   Score  Salary  Grade  Passion
Pavan  25.0  30.0   8000.0  F      Fish       1
Uday   0.0   60.0   1.0     C      45         1
Name: count, dtype: int64

In [47]:
df.describe() # count,mean,std,min,25%,50%,75%,max

             Age      Score        Salary
count   7.000000   6.000000      6.000000
mean   21.000000  69.833333   8083.500000
std    12.247449  23.103391   7901.799384
min     0.000000  30.000000      1.000000
25%    15.500000  63.000000   2625.000000
50%    22.000000  73.000000   5500.000000
75%    29.000000  84.500000  13250.000000
max    36.000000  95.000000  20000.000000

In [16]:
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

# B Clean The Data, Detecting Missing,Duplicates and Filling the Data

# df.isnull(),.isnull().sum(),.isnull().sum().sum()......  # Shows Nan Or None Values

In [2]:
df1=df.isnull() # isnull() show True means NaN or None values and False valid Values
df1

    Name    Age  Score  Salary  Grade  Passion
0  False  False  False   False  False    False
1  False   True  False    True  False    False
2  False  False   True   False   True    False
3  False   True  False   False  False    False
4  False  False   True    True  False    False
5  False  False  False   False   True    False
6  False  False  False   False  False    False
7  False  False   True   False  False    False
8  False  False  False    True  False    False

In [4]:
df11=df.isnull().sum() # isnull().sum() NaN or None values column wise
df11

Name       0
Age        2
Score      3
Salary     3
Grade      2
Passion    0
dtype: int64

In [6]:
df111=df.isnull().sum().sum() # Whole table NaN or None Values you have
df111

np.int64(10)

In [ ]:
# df=df.dropna(),.dropna(subset=['']),.dropna(axis=1) # Drops the Nan or None Values

In [7]:
df2=df.dropna() # Drops all NaN or None values , shows only valid row values
df2

    Name   Age  Score  Salary Grade Passion
0  Pavan  25.0   30.0  8000.0     F    Fish
6   Uday   0.0   60.0     1.0     C      45

In [9]:
df22=df.dropna(subset=['Age']) # drop N,None values in Age Column it shows only valid values in Age
df22

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
2      Divya  22.0    NaN  20000.0  None   Skippin
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

In [17]:
df222=df.dropna(subset=['Salary','Score','Grade']) # drops Nan,None values in Salary,Score,Grade.It shows only valid values of Salar,Score,Grade
df222

        Name   Age  Score   Salary Grade  Passion
0      Pavan  25.0   30.0   8000.0     F     Fish
3  Rahim Sir   NaN   88.0  15000.0    A+  Studies
6       Uday   0.0   60.0      1.0     C       45

In [15]:
df2222=df.dropna(axis=1)
df2222

        Name   Passion
0      Pavan      Fish
1  Narasimha   Cricket
2      Divya   Skippin
3  Rahim Sir   Studies
4  Pathi Sir  Football
5     Swetha   Drawing
6       Uday        45
7     Yasmin   Reading
8     Saddam   Singing

In [15]:
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

# df=df.fillna(), .fillna(df[''].mean()), .fillna(df[''].max())........ # Filling the Data with necessary inputs

In [19]:
df3=df.fillna(56) 
df3

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha  56.0   95.0     56.0     A   Cricket
2      Divya  22.0   56.0  20000.0    56   Skippin
3  Rahim Sir  56.0   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0   56.0     56.0     B  Football
5     Swetha  18.0   72.0   3000.0    56   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0   56.0   2500.0         Reading
8     Saddam  36.0   74.0     56.0     C   Singing

In [20]:
df33=df.fillna(df['Age'].mean())
df33

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha  21.0   95.0     21.0     A   Cricket
2      Divya  22.0   21.0  20000.0  21.0   Skippin
3  Rahim Sir  21.0   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0   21.0     21.0     B  Football
5     Swetha  18.0   72.0   3000.0  21.0   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0   21.0   2500.0         Reading
8     Saddam  36.0   74.0     21.0     C   Singing

In [23]:
# Shortcut for filling all columns at a time
df333=df.fillna({
    'Age':df['Age'].mean(),
    'Score':df['Score'].max(),
    'Salary':df['Salary'].std(),
    'Grade':df['Grade'].ffill()
})

df333

        Name   Age  Score        Salary Grade   Passion
0      Pavan  25.0   30.0   8000.000000     F      Fish
1  Narasimha  21.0   95.0   7901.799384     A   Cricket
2      Divya  22.0   95.0  20000.000000     A   Skippin
3  Rahim Sir  21.0   88.0  15000.000000    A+   Studies
4  Pathi Sir  33.0   95.0   7901.799384     B  Football
5     Swetha  18.0   72.0   3000.000000     B   Drawing
6       Uday   0.0   60.0      1.000000     C        45
7     Yasmin  13.0   95.0   2500.000000         Reading
8     Saddam  36.0   74.0   7901.799384     C   Singing

In [14]:
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

# Selectting Indexing

In [48]:
df['Age'] # Getting only Age column values

0    25.0
1     NaN
2    22.0
3     NaN
4    33.0
5    18.0
6     0.0
7    13.0
8    36.0
Name: Age, dtype: float64

In [52]:
df[['Age','Score']] # Get Age,Score column values

    Age  Score
0  25.0   30.0
1   NaN   95.0
2  22.0    NaN
3   NaN   88.0
4  33.0    NaN
5  18.0   72.0
6   0.0   60.0
7  13.0    NaN
8  36.0   74.0

In [56]:
df.loc[3] # first row - like a table data , loc is accessing int

Name       Rahim Sir
Age              NaN
Score           88.0
Salary       15000.0
Grade             A+
Passion      Studies
Name: 3, dtype: object

In [55]:
df.iloc[3] # iloc is access only with int

Name       Rahim Sir
Age              NaN
Score           88.0
Salary       15000.0
Grade             A+
Passion      Studies
Name: 3, dtype: object

In [57]:
df.loc[0:3] # 3 inclusive

        Name   Age  Score   Salary Grade  Passion
0      Pavan  25.0   30.0   8000.0     F     Fish
1  Narasimha   NaN   95.0      NaN     A  Cricket
2      Divya  22.0    NaN  20000.0  None  Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+  Studies

In [58]:
df.iloc[0:3] # 3 exclusive

        Name   Age  Score   Salary Grade  Passion
0      Pavan  25.0   30.0   8000.0     F     Fish
1  Narasimha   NaN   95.0      NaN     A  Cricket
2      Divya  22.0    NaN  20000.0  None  Skippin

In [60]:
df.loc[2,['Name']] # loc is accessing int and object

Name    Divya
Name: 2, dtype: object

In [10]:
df.iloc[0:3,0:1]

        Name
0      Pavan
1  Narasimha
2      Divya

In [9]:
df.iloc[2:3,2:5]

   Score   Salary Grade
2    NaN  20000.0  None

In [13]:
df

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading
8     Saddam  36.0   74.0      NaN     C   Singing

# Filtering Data with &,|,~,.isin,.between,.str.contains,.query

In [12]:
df['Age']>30

0    False
1    False
2    False
3    False
4     True
5    False
6    False
7    False
8     True
Name: Age, dtype: bool

In [24]:
df[(df['Age']>30)&(df['Score']>50)]

     Name   Age  Score  Salary Grade  Passion
8  Saddam  36.0   74.0     NaN     C  Singing

In [28]:
df[~(df['Name']=='Saddam')]

        Name   Age  Score   Salary Grade   Passion
0      Pavan  25.0   30.0   8000.0     F      Fish
1  Narasimha   NaN   95.0      NaN     A   Cricket
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
5     Swetha  18.0   72.0   3000.0  None   Drawing
6       Uday   0.0   60.0      1.0     C        45
7     Yasmin  13.0    NaN   2500.0         Reading

In [29]:
df[(df['Age']>30) | (df['Salary']>10000)]

        Name   Age  Score   Salary Grade   Passion
2      Divya  22.0    NaN  20000.0  None   Skippin
3  Rahim Sir   NaN   88.0  15000.0    A+   Studies
4  Pathi Sir  33.0    NaN      NaN     B  Football
8     Saddam  36.0   74.0      NaN     C   Singing

In [34]:
df[df['Name'].isin(['Yasmin','Enus'])]

     Name   Age  Score  Salary Grade  Passion
7  Yasmin  13.0    NaN  2500.0        Reading

In [35]:
df[df['Age'].between(20,30)]

    Name   Age  Score   Salary Grade  Passion
0  Pavan  25.0   30.0   8000.0     F     Fish
2  Divya  22.0    NaN  20000.0  None  Skippin

In [39]:
df[df['Name'].str.contains("m")]

        Name   Age  Score   Salary Grade  Passion
1  Narasimha   NaN   95.0      NaN     A  Cricket
3  Rahim Sir   NaN   88.0  15000.0    A+  Studies
7     Yasmin  13.0    NaN   2500.0        Reading
8     Saddam  36.0   74.0      NaN     C  Singing

In [41]:
df.query('Age>30')

        Name   Age  Score  Salary Grade   Passion
4  Pathi Sir  33.0    NaN     NaN     B  Football
8     Saddam  36.0   74.0     NaN     C   Singing